export default {

  GAME_CHANGE_COUNTS: 'GAME_CHANGE_COUNTS',
  GAME_CHANGE_PRODUCTIONS: 'GAME_CHANGE_PRODUCTIONS',
  GAME_CHANGE_GAME_STATE: 'GAME_CHANGE_GAME_STATE',
  GAME_SET_GAME_STATE: 'GAME_SET_GAME_STATE',

  UI_ADD_HISTORY: 'UI_ADD_HISTORY',
  UI_HIDE_MODAL: 'UI_HIDE_MODAL',
  UI_REDO: 'UI_REDO',
  UI_SET_HISTORY: 'UI_SET_HISTORY',
  UI_SHOW_MODAL: 'UI_SHOW_MODAL',
  UI_START_GAME: 'UI_START_GAME',
  UI_UNDO: 'UI_UNDO'

}